package Shape;

public class ShapeDemo  {
public static void main(String[] args) {
	Circle circle=new Circle(30);
	circle.calcArea();
	circle.calcVolume();
	Square square=new Square(20);
	square.calcArea();
	square.calcVolume();
	Triangle triangle=new Triangle(40,20,30);
	triangle.calcArea();
	triangle.calcVolume();
	Sphere sphere=new Sphere(70);
	sphere.calcArea();
	sphere.calcPerimeter();
	sphere.calcVolume();
	sphere.calcSurfaceArea();
}
}
interface Shape
{
	public void calcArea();
	public void calcVolume();
}
class Circle implements Shape
{
	private int radius;
	
	public final int getRadius() {
		return radius;
	}
	public final void setRadius(int radius) {
		this.radius = radius;
	}
	public Circle(int radius)
	{
		this.radius=radius;
	}
	@Override
	public void calcArea() {
		// TODO Autogenerated method stub
		int area=(int)(3.14)*radius*radius;
		System.out.println(area);
	}

	@Override
	public void calcVolume() {
		// TODO Auto-generated method stub
		int volume=2*(int)(3.14)*radius;
		System.out.println(volume);
		
	}
	
}
class Square implements Shape
{
	private int radius;
	public final int getRadius() {
		return radius;
	}
	public final void setRadius(int radius) {
		this.radius = radius;
	}
	Square(int radius)
	{
		this.radius=radius;
	}
	@Override
	public void calcArea() {
		// TODO Autogenerated method stub
		int area=radius*radius;
		System.out.println(area);
	}

	@Override
	public void calcVolume() {
		// TODO Auto-generated method stub
		int volume=4*radius;
		System.out.println(volume);
		
	}
	
}
class Triangle implements Shape
{
	private int a;
	private int b;
	private int c;
	Triangle(int a,int b,int c)
	{
		this.a=a;
		this.b=b;
		this.c=c;
	}
	public final int getA() {
		return a;
	}
	public final void setA(int a) {
		this.a = a;
	}
	public final int getB() {
		return b;
	}
	public final void setB(int b) {
		this.b = b;
	}
	public final int getC() {
		return c;
	}
	public final void setC(int c) {
		this.c = c;
	}
	@Override
	public void calcArea() {
		// TODO Autogenerated method stub
		int area=(getA()+getB()+getC())/2;
		System.out.println(area);
	}

	@Override
	public void calcVolume() {
		// TODO Auto-generated method stub
		int volume=getA()+getB()+getC();
		System.out.println(volume);
		
	}
	
}
class Sphere implements Shape
{
	private int radius;
	
	public final int getRadius() {
		return radius;
	}
	public final void setRadius(int radius) {
		this.radius = radius;
	}
	public Sphere(int radius)
	{
		this.radius=radius;
	}
	@Override
	public void calcArea() {
		// TODO Autogenerated method stub
		int area=(int)(3.14)*getRadius()*getRadius();
		System.out.println(area);
	}

	@Override
	public void calcVolume() {
		// TODO Auto-generated method stub
		int volume=2*(int)(3.14)*radius;
		System.out.println(volume);
		
	}
	public void calcSurfaceArea()
	{
		int surfaceArea=4*getRadius()*getRadius();
		System.out.println(surfaceArea);
	}
	public void calcPerimeter()
	{
		int perimeter=(int)(4/3)*(int)(3.14)*getRadius()*getRadius();
		System.out.println(perimeter);
	}
}
